# workflow name
name: Deploy Article


on:
  push:
  schedule:
    - cron: '0 16 * * *'

jobs:
  build: 
    runs-on: ubuntu-latest 
        
    steps:
    # check it to your workflow can access it
    # from: https://github.com/actions/checkout
    - name: Checkout Repository master branch
      uses: actions/checkout@master 
      
    # from: https://github.com/actions/setup-node  
    
    - name: Setup
      run: |
        pip3 install beautifulsoup4
    - name: Setup
      run: |
        python3 gen.py
    - name: Setup Deploy Private Key
      env:
        DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-keyscan e.coding.net >> ~/.ssh/known_hosts
        
    - name: Setup Git Infomation
      run: |
        git config --global user.name 'MicDZ' 
        git config --global user.email 'micdzcn@gmail.com'
    - name: Deploy 
      run: |
        git add .
        git commit -m "Update."
        git push -u origin master
