# master branch on push, auto run
on:
  push:
  schedule:
    - cron: '0 22 * * *'
      
jobs:
  build: 
    runs-on: ubuntu-latest 
        
    steps:
    # check it to your workflow can access it
    # from: https://github.com/actions/checkout
    - name: Checkout Repository master branch
      uses: actions/checkout@master 
    
    - name: Setup Deploy Private Key
      env:
        DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY_BOT }}
      run: |
        mkdir -p ~/.ssh/
        echo "$DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        
    - name: Setup Git Infomation
      run: | 
        git config --global user.name 'micdzbot' 
        git config --global user.email 'bot@micdz.cn'
    - name: Update
      run: | 
        git clone "git@github.com:MicDZ/Daily-Learning-Site.git"
        pip3 install beautifulsoup4 
        python3 gen.py
        cd Daily-Learning-Site
        git add .
        git commit -m "Update."
        git push origin master